export const destinations = [
  {
    id: 1,
    title: "Maldives",
    country: "Maldives",
    duration: "7 Days",
    price: "$4,900",
    rating: 4.9,
    image: "/images/maldives.jpg",
    featured: true,
  },
  {
    id: 2,
    title: "Dubai",
    country: "UAE",
    duration: "5 Days",
    price: "$2,700",
    rating: 4.8,
    image: "/images/dubai.jpg",
  },
  {
    id: 3,
    title: "Kyoto",
    country: "Japan",
    duration: "8 Days",
    price: "$3,900",
    rating: 4.9,
    image: "/images/kyoto.jpg",
  },
  {
    id: 4,
    title: "Bali",
    country: "Indonesia",
    duration: "6 Days",
    price: "$2,600",
    rating: 4.8,
    image: "/images/bali.jpg",
  },
  {
    id: 5,
    title: "Santorini",
    country: "Greece",
    duration: "6 Days",
    price: "$3,500",
    rating: 4.9,
    image: "/images/santorini.jpg",
  },
  {
    id: 6,
    title: "Swiss Alps",
    country: "Switzerland",
    duration: "9 Days",
    price: "$5,800",
    rating: 5.0,
    image: "/images/swiss.jpg",
  },
];